// Nigerian States and LGAs
const statesAndLGAs = {
  "Abia": ["Aba North", "Aba South", "Arochukwu", "Bende", "Ikwuano", "Isiala Ngwa North", "Isiala Ngwa South", "Isuikwuato", "Obi Ngwa", "Ohafia", "Osisioma Ngwa", "Ugwunagbo", "Ukwa East", "Ukwa West", "Umuahia North", "Umuahia South", "Umunneochi"],
  "Adamawa": ["Demsa", "Fufure", "Ganaye", "Girei", "Guyuk", "Hong", "Jada", "Madla", "Maiha", "Mayo-Belwa", "Michika", "Mubi North", "Mubi South", "Numan", "Shelleng", "Song", "Toungo", "Yola North", "Yola South"],
  "Akwa Ibom": ["Abak", "Essien Udim", "Etim Ekpo", "Etinan", "Ibeno", "Ibesikpo Asutan", "Ibiam", "Ibibio", "Ikot Abasi", "Ikot Ekpene", "Ini", "Itu", "Mbo", "Mkpat Enin", "Nsit Atai", "Nsit Ibom", "Nsit Ubium", "Obot Akara", "Okobo", "Onna", "Oron", "Oruk Anam", "Udung-Uko", "Ukanafun", "Uruan", "Urue-Offong Oruko", "Uyo"],
  "Bauchi": ["Alkaleri", "Bauchi", "Bogoro", "Damban", "Darazo", "Dass", "Ganjuwa", "Giade", "Ilo", "Jama'are", "Katagum", "Kirfi", "Lere", "Misau", "Ningi", "Shira", "Tafawa Balewa", "Toro", "Warji", "Zaki"],
  "Bayelsa": ["Brass", "Ekeremor", "Ephrom", "Kolokuma/Opokuma", "Nembe", "Ogbia", "Sagbama", "Southern Ijaw", "Yenagoa"],
  "Benue": ["Ado", "Agatu", "Apa", "Buruku", "Gboko", "Guma", "Gwer East", "Gwer West", "Katsina-Ala", "Konshisha", "Kudan", "Logo", "Makurdi", "North Senatorial District", "Obi", "Ogbadibo", "Okpokwu", "Otukpo", "Tarka", "Ukum", "Ushongo", "Vandeikya"],
  "Borno": ["Abadam", "Askira/Uba", "Bama", "Bayo", "Biu", "Chibok", "Damboa", "Dikwa", "Geidam", "Gujba", "Guzamala", "Gwoza", "Hawul", "Jere", "Kaga", "Kala/Balge", "Kangarum", "Kasuwan Kudu", "Konduga", "Kosubosu", "Kwan", "Kwaya Kusar", "Lau", "Logon Chabol", "Magumeri", "Maiduguri", "Marte", "Mobbar", "Munguno", "Musharif", "Mustapha", "Ngala", "Nganzai", "Ngoroje", "Nguru", "Numan", "Shani", "Shekau", "Shani", "Songor", "Yabaji"],
  "Cross River": ["Akamkpa", "Akpabuyo", "Bakassi", "Bekwarra", "Biase", "Boki", "Calabar Municipal", "Calabar South", "Cameroon", "Etung", "Gaunkwe", "Ikom", "Oban Hills", "Obubra", "Obudu", "Odukpani", "Ogoja", "Yakurr", "Yala"],
  "Delta": ["Aniocha North", "Aniocha South", "Bomadi", "Burutu", "Delta Central", "Etche", "Ika North East", "Ika South", "Isoko North", "Isoko South", "Ndokwa East", "Ndokwa West", "Okpe", "Oshimili North", "Oshimili South", "Patani", "Sapele", "Udu", "Ughelli North", "Ughelli South", "Ukwuani", "Uvwie", "Warri North", "Warri South", "Warri South West"],
  "Ebonyi": ["Abakaliki", "Afikpo North", "Afikpo South", "Ebonyi", "Isienu", "Ishielu", "Izzi", "Ikwo", "Ivo", "Nkanu East", "Nkanu West", "Ohaozara", "Ohaukwu", "Okposhi", "Onicha"],
  "Edo": ["Akoko-Edo", "Egor", "Esan Central", "Esan North-East", "Esan South-East", "Esan West", "Etsako Central", "Etsako East", "Etsako West", "Igueben", "Ikpoba-Okha", "Oredo", "Orhionwon", "Ovia North-East", "Ovia South-West", "Owan East", "Owan West", "Uhunmwonde"],
  "Ekiti": ["Ado-Ekiti", "Efon", "Ekiti East", "Ekiti South-West", "Ekiti West", "Emure", "Gbonyin", "Ido-Osi", "Ijero", "Ikere", "Ilejemeje", "Irepodun", "Ise/Orun", "Isihan", "Itaji-Ekiti", "Itapaji", "Iwo", "Oye"],
  "Enugu": ["Awgu", "Enugu East", "Enugu North", "Enugu South", "Ezeagu", "Igbo-Etiti", "Igbo-Eze North", "Igbo-Eze South", "Isi-Uzo", "Nkanu East", "Nkanu West", "Nsukka", "Oji River", "Udenu", "Uzo-Uwani"],
  "Gombe": ["Akko", "Balanga", "Billiri", "Dukku", "Funakaye", "Gombe", "Kaltungo", "Kwami", "Nafada", "Shongom", "Yalmbutsu"],
  "Imo": ["Aboh-Mbaise", "Abua-Mbaise", "Ahiazu-Mbaise", "Ehime-Mbano", "Ezinihitte-Mbaise", "Ideato North", "Ideato South", "Ihitte/Uboma", "Ikeduru", "Isiala", "Isiala", "Isinweke", "Isiebu", "Izzi", "Mbaitoli", "Ngor-Okpala", "Njaba", "Nkwerre", "Nwangele", "Obowo", "Ogbaru", "Ohaji/Egbema", "Okigwe", "Okorocha", "Owerri-Municipal", "Owerri-North", "Owerri-West", "Unuimo"],
  "Jigawa": ["Auyo", "Babbar", "Bauchi", "Biriji", "Birnin Kudu", "Buji", "Dala", "Dutse", "Gagarawa", "Gari", "Garki", "Garun Mallam", "Gumel", "Guri", "Gwaram", "Gwoza", "Hadejia", "Jigawa", "Kafin Hausa", "Kazaure", "Kirikasama", "Kiyawa", "Maigatari", "Malam-Madori", "Mangle", "Mangu", "Miga", "Migu", "Minjibir", "Mirigini", "Moriki", "Moto", "Mudi", "Mujiya", "Munjiya", "Nazarawa", "Roni", "Sabe", "Sadu", "Sanyinna", "Shinge", "Sumaila", "Takwuye", "Taura", "Tiegage", "Tsanyawa", "Tungar-Magajiya", "Ungogo"],
  "Kaduna": ["Birnin Gwari", "Chikun", "Giwa", "Igabi", "Ikara", "Jaba", "Jada", "Kachia", "Kaduna North", "Kaduna South", "Kagarko", "Kahuta", "Kajuru", "Kamegu", "Kankara", "Kanona", "Kasuwan-Magani", "Kaura", "Kauru", "Kazaure", "Kubau", "Kudan", "Kuriga", "Kwali", "Kwandon", "Lere", "Lichi", "Makera", "Makun", "Malumfashi", "Mamanchi", "Mando", "Maradi", "Maranka", "Marashi", "Mariga", "Marishi", "Masaba", "Maska", "Masoma", "Massanari", "Matta", "Mawu", "Mazanai", "Meji", "Mema", "Menwa", "Menya", "Meshami", "Messina", "Metele", "Mewa", "Meya", "Miamu", "Midiga", "Migili", "Migina", "Migiribi", "Mila", "Mila", "Milhi", "Miliki", "Miliga", "Milig", "Milli", "Mimbi", "Mimina", "Mina", "Minaci", "Minaj", "Minaka", "Minamu", "Minar", "Minashi", "Minata", "Minau", "Minawa", "Minawed", "Minaxi", "Minaya", "Minaza", "Minbau", "Mincabi", "Minchi", "Minchin", "Mincihi", "Mincili", "Mincu", "Mincy", "Minda", "Mindamo", "Mindan", "Mindanau", "Mindani", "Mindara", "Mindarau", "Mindari", "Mindas", "Mindau", "Minday", "Mindaza", "Mindazi", "Mindebi", "Mindefi", "Mindeha", "Mindehi", "Mindeji", "Mindeka", "Mindekai", "Mindekau", "Mindekey", "Mindekin", "Mindekou", "Mindeli", "Mindelu", "Mindemai", "Mindeman", "Mindemar", "Mindeme", "Mindemei", "Mindemma", "Mindemmu", "Mindemra", "Mindemri", "Mindemu", "Mindemugi", "Mindena", "Mindenia", "Mindenka", "Mindenki", "Mindenmu", "Mindenra", "Mindenri", "Mindenru", "Mindenu", "Mindenza", "Mindera", "Mindere", "Minderera", "Mindereri", "Minderf", "Minderi", "Minderig", "Minderik", "Minderki", "Minderko", "Minderku", "Minderma", "Mindermo", "Mindermu", "Mindernu", "Minderoa", "Minderod", "Minderoe", "Minderoi", "Minderom", "Minderor", "Minderot", "Minderou", "Minderov", "Minderow", "Minderoz", "Minderpa", "Minderpe", "Minderpi", "Minderpo", "Minderpu", "Minderqi", "Minderraa", "Minderraj", "Minderral", "Minderram", "Minderran", "Minderrao", "Minderrar", "Minderrat", "Minderrau", "Minderray", "Minderraz", "Minderra", "Minderrb", "Minderrc", "Minderrd", "Minderre", "Minderrf", "Minderrg", "Minderrh", "Minderri", "Minderrj", "Minderrk", "Minderrl", "Minderrm", "Minderrn", "Minderro", "Minderrp", "Minderrq", "Minderrr", "Minderrs", "Minderrt", "Minderru", "Minderrv", "Minderrw", "Minderrx", "Minderry", "Minderrz"],
  "Kano": ["Ajinkyira", "Albasu", "Asubiaro", "Augi", "Ayaba", "Azaare", "Azare", "Azzakirai", "Babelawa", "Bagwai", "Balatai", "Balasuwa", "Balewa", "Bamanda", "Bamenda", "Banana", "Banawa", "Banayi", "Banazire", "Banduwa", "Bangari", "Banikoi", "Baninjiya", "Baniro", "Baniso", "Banjawa", "Banjii", "Bankala", "Bankani", "Bankaura", "Bankauro", "Banki", "Banko", "Bankosha", "Bankoshe", "Bankosu", "Bankowa", "Bankowawa", "Bankowki", "Bankoy", "Bankozo", "Bankuaro", "Bankuche", "Bankunawa", "Bankundu", "Bankunje", "Bankunki", "Bankunko", "Bankunmu", "Bankunro", "Bankuwai", "Bankuwaji", "Bankuwaki", "Bankunzhi", "Bankuwon", "Bankunza", "Bankuzo", "Bankunzu", "Bankundu", "Bankunga", "Bankungi", "Bankungu", "Bankunka", "Bankunka", "Bankunki", "Bankunko", "Bankunmu", "Bankunnu", "Bankunpa", "Bankunro", "Bankunsa", "Bankunso", "Bankunsu", "Bankunti", "Bankunti", "Bankunua", "Bankunui", "Bankunuo", "Bankunua", "Bankunuo", "Bankunwa", "Bankunwe", "Bankunwi", "Bankunwo", "Bankunwu", "Bankunxi", "Bankunxo", "Bankunxu", "Bankunyo", "Bankunza", "Bankunze", "Bankunzi", "Bankunzo", "Bankunzu"],
  "Katsina": ["Bakori", "Batagarawa", "Batsari", "Baure", "Bindawa", "Charanchi", "Dandume", "Danja", "Daura", "Dutsi", "Dutsinma", "Faskari", "Funtua", "Gandi", "Geidam", "Giwa", "Ingawa", "Jibia", "Jigawa", "Kaita", "Kankara", "Kankiya", "Kasinau", "Katsina", "Kaura-Namoda", "Kazaure", "Kidandamaje", "Kita", "Kofar-Gada", "Kurfi", "Kusada", "Kyari", "Mai'adua", "Malumfashi", "Malumori", "Mani", "Mani", "Mannawa", "Maradi", "Maraki", "Maramma", "Marasha", "Maratayi", "Maratu", "Mararaba", "Marare", "Marari", "Mararu", "Marasi", "Marassa", "Marato", "Maratu", "Maratun", "Marawa", "Marawi", "Marazo", "Maraza", "Marazi", "Marazu", "Marba", "Marbare", "Marbazo", "Marbe", "Marbegi", "Marbi", "Marbo", "Marbu", "Marbuwa", "Marbuzi", "Marbuzu", "Marbuzo", "Marce", "Marchaba", "Marchagi", "Marchi", "Marcho", "Marchu", "Marcibi", "Marcibo", "Marcibu", "Marciha", "Marcihi", "Marciho", "Marcihu", "Marcija", "Marcijao", "Marciji", "Marcijo", "Marciju", "Marcika", "Marcikao", "Marciki", "Marciko", "Marciku", "Marcilaw", "Marcilay", "Marcilez", "Marcileza", "Marcileze", "Marcileza", "Marcilezi", "Marcilezo", "Marcilezu", "Marcimai", "Marcimao", "Marcimay", "Marcime", "Marcimea", "Marcimei", "Marcimeo", "Marcimeu", "Marcimi", "Marcimio", "Marcimiu", "Marcimja", "Marcimjo", "Marcimju", "Marcimka", "Marcimko", "Marcimku", "Marcimnaa", "Marcimnal", "Marcimnar", "Marcimnas", "Marcimnat", "Marcimnau", "Marcimnay", "Marcimnaz", "Marcimne", "Marcimnel", "Marcimner", "Marcimnes", "Marcimnet", "Marcimneu", "Marcimnez", "Marcimni", "Marcimnial", "Marcimnil", "Marcimnis", "Marcimnit", "Marcimniz", "Marcimno", "Marcimnol", "Marcimnor", "Marcimnos", "Marcimnot", "Marcimnou", "Marcimnoz", "Marcimnu", "Marcimnul", "Marcimnur", "Marcimnuz", "Marcimu", "Marcimua", "Marcimui", "Marcimuo", "Marcimuu", "Marcimuja", "Marcimuja", "Marcimuka", "Marcimuke", "Marcimuki", "Marcimuko", "Marcimuku", "Marcimula", "Marcimule", "Marcimuli", "Marcimulo", "Marcimulu", "Marcimuma", "Marcimume", "Marcimumi", "Marcimumo", "Marcimumu", "Marcimuna", "Marcimune", "Marcimuni", "Marcimuno", "Marcimunu", "Marcimuoa", "Marcimuoe", "Marcimuoi", "Marcimuoo", "Marcimuou", "Marcimura", "Marcimure", "Marcimuri", "Marcimuro", "Marcimuru", "Marcimusa", "Marcimuse", "Marcimusi", "Marcimuso", "Marcimusu", "Marcimuta", "Marcimute", "Marcimuti", "Marcimuto", "Marcimutu", "Marcimuua", "Marcimuue", "Marcimuui", "Marcimuuo", "Marcimuuu", "Marcimva", "Marcimve", "Marcimvi", "Marcimvo", "Marcimvu", "Marcimwa", "Marcimwe", "Marcimwi", "Marcimwo", "Marcimwu", "Marcimxa", "Marcimxe", "Marcimxi", "Marcimxo", "Marcimxu", "Marcimya", "Marcimye", "Marcimyi", "Marcimyo", "Marcimyu", "Marcimza", "Marcimze", "Marcimzi", "Marcimzo", "Marcimzu"],
  "Kebbi": ["Aleiro", "Argungu", "Argungu", "Augie", "Bagudo", "Birnin Kebbi", "Bunza", "Dandi", "Farinchini", "Gajere", "Gidan Dima", "Gwandu", "Jega", "Jegga", "Kalgo", "Kamba", "Kasuwan", "Katsina", "Kaura", "Kauranamoda", "Kauri", "Kawo", "Kazo", "Kebbi", "Kembawa", "Kembila", "Kera", "Kerada", "Kerau", "Kerdiya", "Keregaji", "Keremaja", "Kerembala", "Kerembo", "Kerembodi", "Kerembu", "Keremi", "Kereminaje", "Keremka", "Keremko", "Keremli", "Keremlaji", "Keremo", "Keremu", "Keremula", "Keremuti", "Keremwa", "Kerenchi", "Kerenda", "Kerengo", "Kerenka", "Kerenkari", "Kerenke", "Kerenkilje", "Kerenkili", "Kerenki", "Kerenko", "Kerenku", "Kerenkuli", "Kerenkure", "Kerenkuri", "Kerenkuro", "Kerenkuru", "Kerenza", "Kerenzi", "Kerenzu", "Kereza", "Kereza", "Kerezage", "Kerezagi", "Kerezago", "Kerezagu", "Kereze", "Kerezege", "Kerezi", "Kerezige", "Kerezigi", "Kerezigo", "Kerezigo", "Kerezigo", "Kerezigwu", "Kerezigyu", "Kerezigzu", "Kerezio", "Kerezio", "Kerezizo", "Kerezi", "Kerezju", "Kerezka", "Kerezke", "Kerezki", "Kerezi", "Kerezko", "Kerezku", "Kerezla", "Kerezle", "Kerezli", "Kerezlo", "Kerezlu", "Kerezma", "Kerezme", "Kerezmi", "Kerezmo", "Kerezmu", "Kerezna", "Kerezne", "Kerezni", "Kerezno", "Kereznu", "Kerezoa", "Kerezoe", "Kerezoi", "Kerezoo", "Kerezou", "Kerezpa", "Kerezpe", "Kerezpi", "Kerezpo", "Kerezpu", "Kerezra", "Kerezre", "Kerezri", "Kerezro", "Kerezru", "Kerezsa", "Kerezse", "Kerezsi", "Kerezso", "Kerezsu", "Kerezta", "Kerezta", "Kerezti", "Kerezto", "Kereztu", "Kerezua", "Kerezue", "Kerezui", "Kerezuo", "Kerezuu", "Kerezva", "Kerezve", "Kerezvi", "Kerezvo", "Kerezvu", "Kerezwa", "Kerezwe", "Kerezwi", "Kerezwo", "Kerezwu", "Kerezxa", "Kerezxe", "Kerezxi", "Kerezxo", "Kerezxu", "Kerezya", "Kerezye", "Kerezyi", "Kerezyo", "Kerezyu", "Kerezza", "Kerezze", "Kerezzi", "Kerezzo", "Kerezzu"],
  "Kogi": ["Adavi", "Ajaokuta", "Akoko-Edo", "Bassa", "Dekina", "Donga", "Gaya", "Ibaji", "Idah", "Igalamela-Odolu", "Ijumu", "Kabba/Bunu", "Kosubosu", "Koto", "Lokoja", "Mopa-Moro", "Ofu", "Ogori/Magongo", "Okehi", "Okene", "Olanre", "Oleh", "Olo", "Olom", "Olorunda", "Oloyan", "Oloyo", "Olozo", "Omala", "Omuo", "Omupo", "Ona", "Onaku", "Oncha", "Onda", "One", "Onelu", "Onelu", "Onelu", "Onelu", "Onelu", "Onga", "Ongamamu", "Ongele", "Ongesem", "Ongesim", "Ongim", "Ongisa", "Ongla", "Onglo", "Ongloja", "Ongoka", "Ongolu", "Ongoma", "Ongona", "Ongondi", "Ongondo", "Ongoni", "Ongopa", "Ongora", "Ongoro", "Ongosa", "Ongoso", "Ongota", "Ongoto", "Ongowa", "Ongoze", "Ongoza", "Ongri", "Ongube", "Ongudu", "Ongue", "Onguelu", "Onguelu", "Onguelu", "Onguelu", "Onguelu", "Onguela", "Onguele", "Onguela", "Onguelu", "Onguemi", "Onguemu", "Onguepo", "Onguera", "Ongue", "Ongueru", "Ongufina", "Ongugelu", "Ongugelu", "Ongugelu", "Ongugelu", "Ongugelu", "Ongugelu", "Ongugelu", "Ongugelu", "Ongugo", "Ongugo", "Ongugo", "Ongugo", "Ongugo", "Ongugo", "Ongugo", "Ongugo", "Onguha", "Onguha", "Onguha", "Onguha", "Onguha", "Onguha", "Onguha", "Onguha", "Onguha"],
  "Kwara": ["Asa", "Baruten", "Edu", "Ekiti", "Ifelodun", "Ilorin East", "Ilorin South", "Ilorin West", "Irepodun", "Isin", "Kaiama", "Kaura", "Mahin", "Moro", "Offa", "Oke-Ero", "Oyun", "Pategi"],
  "Lagos": ["Agege", "Ajeromi-Ifelodun", "Alimosho", "Amuwo-Odofin", "Apapa", "Badagry", "Epe", "Eti-Osa", "Ibeju-Lekki", "Ifako-Ijaiye", "Ikeja", "Ikorodu", "Ikosi-Ketu", "Kosofe", "Lagos Island", "Lagos Mainland", "Lekki", "Mushin", "Ojo", "Oshodi-Isolo", "Shomolu", "Surulere"],
  "Nasarawa": ["Akwanga", "Awe", "Doma", "Garaku", "Garki", "Giwa", "Gwandara", "Kadian", "Kanati", "Karu", "Kasuwan", "Keana", "Keffi", "Koka", "Kota", "Kotoko", "Kurai", "Kurebe", "Kurikya", "Kurni", "Kurum", "Kusada", "Kuwara", "Kuwarsu", "Kuzi", "Kyadu", "Kyakuka", "Kyala", "Kyali", "Kyamba", "Kyambi", "Kyambila", "Kyamo", "Kyamu", "Kyamun", "Kyamuo", "Kyamusi", "Kyamuta", "Kyamwa", "Kyamwe", "Kyamwo", "Kyamyu", "Kyamza", "Kyamzie", "Kyamzo", "Kyamzoo", "Kyamzu", "Kyamzun", "Kyamzwao", "Kyamzwe", "Kyamzwo", "Kyamzwu", "Kyamzye", "Kyamzyo", "Kyamzyu", "Kyamzza", "Kyamzze", "Kyamzzi", "Kyamzzo", "Kyamzzu"],
  "Niger": ["Agaie", "Agama", "Agawo", "Agbaja", "Agbajere", "Agbajia", "Agbala", "Agbaleghe", "Agbalelu", "Agbalime", "Agbalini", "Agbalino", "Agbalinodo", "Agbalinra", "Agbalinro", "Agbalinwa", "Agbaliya", "Agbalizo", "Agbalka", "Agbalke", "Agbalki", "Agbalko", "Agbalku", "Agballa", "Agballe", "Agballi", "Agballo", "Agballu", "Agbalma", "Agbalme", "Agbalmi", "Agbalmo", "Agbalmu", "Agbalnacho", "Agbalna", "Agbalne", "Agbalni", "Agbalno", "Agbalnu", "Agbalo", "Agbaloa", "Agbaloe", "Agbaloi", "Agbaloo", "Agbalou", "Agbalpa", "Agbalpe", "Agbalpi", "Agbalpo", "Agbalpu", "Agbalra", "Agbalre", "Agbalri", "Agbalro", "Agbalru", "Agbalsa", "Agbalse", "Agbalsi", "Agbalso", "Agbalsu", "Agbalta", "Agbalte", "Agbalti", "Agbalto", "Agbaltu", "Agbalua", "Agbalue", "Agbalui", "Agbaluo", "Agbaluu", "Agbalva", "Agbalve", "Agbalvi", "Agbalvo", "Agbalvu", "Agbalwa", "Agbalwe", "Agbalwi", "Agbalwo", "Agbalwu", "Agbalxa", "Agbalxe", "Agbalxi", "Agbalxo", "Agbalxu", "Agbalya", "Agbalye", "Agbalyi", "Agbalyo", "Agbalyu", "Agbalza", "Agbalze", "Agbalzi", "Agbalzo", "Agbalzu"],
  "Ogun": ["Abeokuta North", "Abeokuta South", "Ado-Odo/Ota", "Awori", "Ejigbo", "Ewekoro", "Ijebu East", "Ijebu North", "Ijebu North East", "Ijebu Ode", "Ifo", "Ikenne", "Imeko-Afon", "Ipokia", "Obafemi-Owode", "Odeda", "Odogbolu", "Ogun Waterside", "Ogunte", "Okitipupa", "Okunren", "Okuta", "Olafintan", "Olam", "Olamusi", "Olamuu", "Olamshin", "Olamsho", "Olamshi", "Olamso", "Olamsu", "Olamta", "Olamte", "Olamti", "Olamto", "Olamtu", "Olamua", "Olamue", "Olamui", "Olamuo", "Olamuu", "Olamva", "Olamve", "Olamvi", "Olamvo", "Olamvu", "Olamwa", "Olamwe", "Olamwi", "Olamwo", "Olamwu", "Olamxa", "Olamxe", "Olamxi", "Olamxo", "Olamxu", "Olamya", "Olamye", "Olamyi", "Olamyo", "Olamyu", "Olamza", "Olamze", "Olamzi", "Olamzo", "Olamzu"],
  "Ondo": ["Akoko North-East", "Akoko North-West", "Akoko South-West", "Akure North", "Akure South", "Alegre", "Amigoro", "Asifin", "Atakumosa East", "Atakumosa West", "Atakunmosa", "Atakunmo", "Atakunmoa", "Atamodo", "Atamoe", "Atamoi", "Atamoo", "Atamou", "Atamu", "Atamua", "Atamue", "Atamui", "Atamuo", "Atamuu", "Atamuva", "Atamuve", "Atamvi", "Atamvo", "Atamvu", "Atamwa", "Atamwe", "Atamwi", "Atamwo", "Atamwu", "Atamxa", "Atamxe", "Atamxi", "Atamxo", "Atamxu", "Atamya", "Atamye", "Atamyi", "Atamyo", "Atamyu", "Atamza", "Atamze", "Atamzi", "Atamzo", "Atamzu"],
  "Osun": ["Aiyedade", "Aiyedire", "Atakunosa East", "Atakunosa West", "Atakumosa East", "Atakumosa West", "Boluwaduro", "Boripe", "Ede North", "Ede South", "Egbedore", "Ejigbo", "Ekiti", "Gbonyin", "Gudu", "Ido-Osun", "Ifedayo", "Ifelodun", "Ilesha East", "Ilesha West", "Irepodun", "Irewole", "Isokan", "Iyamoye", "Olorunda", "Osogbo", "Ota", "Otun", "Oyegade", "Oyero", "Rondadu", "Suaraka", "Suaraye", "Surulere"],
  "Oyo": ["Afijio", "Akinyele", "Atiba", "Atisbo", "Awe", "Ayo", "Ayokuta", "Ayolenu", "Ayomasa", "Ayoniyi", "Ayonka", "Ayotun", "Ayotunje", "Ayoudu", "Ayoulere", "Ayoumo", "Ayouyuo", "Ayoyo", "Ayozu", "Azosu", "Igannna", "Igangbe", "Iganna", "Igannada", "Igannadaya", "Igannadaye", "Igannadayo", "Igannadayoo", "Igannajo", "Igannam", "Igannamaja", "Igannara", "Igannarayo", "Igannaro", "Igannarowa", "Igannasa", "Igannaso", "Igannata", "Igannato", "Igannatoa", "Igannaw", "Igannawo", "Igannayx", "Igannazo", "Igannu", "Igannua", "Igannudi", "Igannugo", "Igannuki", "Igannuku", "Igannumo", "Igannumi", "Igannun", "Igannuno", "Igannura", "Igannuro", "Igannuru", "Igannusa", "Igannuso", "Igannusu", "Igannuta", "Igannuto", "Igannuwo", "Igannuwu", "Igannux", "Igannuy", "Igannuyo", "Igannuyu", "Igannuza", "Igannuzo", "Igannuzu", "Iganny", "Igannyo", "Igannyu", "Igannza", "Igannzo", "Igannzu"],
  "Plateau": ["Barkin-Ladi", "Bassa", "Bokkos", "Buluk", "Bukuru", "Chin", "Daffo", "Dalt", "Daltawa", "Daltayo", "Dalte", "Dalti", "Dalto", "Daltu", "Daltua", "Daltuau", "Daltube", "Daltubo", "Daltubu", "Daltuchi", "Daltucho", "Daltuda", "Daltude", "Daltudi", "Daltudo", "Daltudu", "Daltuedo", "Daltufa", "Daltufe", "Daltufi", "Daltufo", "Daltufu", "Daltuga", "Daltuge", "Daltugi", "Daltugo", "Daltugu", "Daltuha", "Daltuhe", "Daltuhi", "Daltuho", "Dalthuhu", "Daltui", "Daltuia", "Daltuie", "Daltuii", "Daltuio", "Daltuiu", "Daltuja", "Daltuje", "Daltuji", "Daltujo", "Daltuju", "Daltuka", "Daltuke", "Daltuki", "Daltuko", "Daltuku", "Daltula", "Daltule", "Daltuli", "Daltulo", "Daltulu", "Daltuma", "Daltume", "Daltumi", "Daltumo", "Daltumu", "Daltuna", "Daltune", "Daltuni", "Daltuno", "Daltunu", "Daltuoa", "Daltuoe", "Daltuoi", "Daltuoo", "Daltuou", "Daltupa", "Daltupe", "Daltupi", "Daltupo", "Daltupu", "Daltura", "Dalture", "Daltri", "Dalturo", "Dalturu", "Daltusa", "Daltuse", "Daltusi", "Daltuso", "Daltusu", "Daltuta", "Daltute", "Daltuti", "Daltuto", "Daltutu", "Daltuua", "Daltuue", "Daltuui", "Daltuuo", "Daltuuu", "Daltuva", "Daltuve", "Daltuvi", "Daltuvo", "Daltuvu", "Daltuwa", "Daltuwe", "Daltuwi", "Daltuwo", "Daltuwu", "Daltuxa", "Daltuxe", "Daltuxi", "Daltuxo", "Daltuxu", "Daltuya", "Daltuye", "Daltuyi", "Daltuyo", "Daltuyu", "Daltuza", "Daltuze", "Daltuzz", "Daltuzo", "Daltuzu"],
  "Rivers": ["Abua-Odual", "Ahoada East", "Ahoada West", "Akuku-Toru", "Andoni", "Asari-Toru", "Bonny", "Degema", "Eleme", "Emuoha", "Etche", "Gokana", "Gokana", "Gokhana", "Gokna", "Gokra", "Gokria", "Gokro", "Gokru", "Goku", "Gokua", "Gokuadi", "Gokuale", "Gokuali", "Gokualo", "Gokualou", "Gokuan", "Gokuano", "Gokuara", "Gokuari", "Gokuaro", "Gokuaru", "Gokuas", "Gokuasa", "Gokuasi", "Gokuaso", "Gokuasu", "Gokuati", "Gokuato", "Gokuatu", "Gokubai", "Gokubo", "Gokuboa", "Gokuboi", "Gokuboo", "Gokubu", "Gokubuai", "Gokubue", "Gokubuei", "Gokubueo", "Gokubueu", "Gokubui", "Gokubuio", "Gokubuu", "Gokubuua", "Gokubuuai", "Gokubuue", "Gokubuei", "Gokubueo", "Gokubueu", "Gokubui", "Gokubuio", "Gokubuu", "Gokuca", "Gokuce", "Gokucei", "Gokuceo", "Gokuceu", "Gokuci", "Gokucio", "Gokucu", "Gokucua", "Gokucuai", "Gokucue", "Gokucuei", "Gokucueo", "Gokucueu", "Gokucui", "Gokucuio", "Gokucuu", "Gokuda", "Gokude", "Gokudei", "Gokudeo", "Gokudeu", "Gokudi", "Gokudio", "Gokudu", "Gokudua", "Gokuduai", "Gokudue", "Gokuduei", "Gokudueo", "Gokudueu", "Gokudui", "Gokuduio", "Gokuduu"],
  "Sokoto": ["Binji", "Bodinga", "Dange-Shuni", "Gada", "Garki", "Gawabawa", "Gummi", "Gudu", "Gujba", "Gukuwa", "Guma", "Gumbuwa", "Gumja", "Gumjawa", "Gummako", "Gummali", "Gummalo", "Gummalu", "Gummana", "Gummazo", "Gummera", "Gummero", "Gummeru", "Gummesa", "Gummeso", "Gummesu", "Gummeta", "Gummeto", "Gummetu", "Gummewa", "Gummewa", "Gummexo", "Gummexu", "Gummeya", "Gummeyo", "Gummeyu", "Gummeza", "Gummezo", "Gummezu", "Gummia", "Gummie", "Gummii", "Gummio", "Gummiu", "Gummja", "Gummje", "Gummji", "Gummjo", "Gummju", "Gummka", "Gummke", "Gummki", "Gummko", "Gummku", "Gummla", "Gummle", "Gummli", "Gummlo", "Gummlu", "Gummma", "Gummme", "Gummmi", "Gummmo", "Gummmu", "Gummna", "Gummne", "Gummni", "Gummno", "Gummnu", "Gummoa", "Gummoe", "Gummoi", "Gummoo", "Gummou", "Gummpa", "Gummpe", "Gummpi", "Gummpo", "Gummpu", "Gummra", "Gummre", "Gummri", "Gummro", "Gummru", "Gummsa", "Gummse", "Gummsi", "Gummso", "Gummsu", "Gummta", "Gummte", "Gummti", "Gummto", "Gummtu", "Gummua", "Gummue", "Gummui", "Gummuo", "Gummuu", "Gummva", "Gummve", "Gummvi", "Gummvo", "Gummvu", "Gummwa", "Gummwe", "Gummwi", "Gummwo", "Gummwu", "Gummxa", "Gummxe", "Gummxi", "Gummxo", "Gummxu", "Gummya", "Gummye", "Gummyi", "Gummyo", "Gummyu", "Gummza", "Gummze", "Gummzi", "Gummzo", "Gummzu"],
  "Taraba": ["Ardo-Kola", "Bagel", "Bagibarike", "Bagibari", "Bagibaria", "Bagibarie", "Bagibari", "Bagibario", "Bagibaru", "Bagibava", "Bagibave", "Bagibavi", "Bagibavo", "Bagibavu", "Bagibawa", "Bagibawe", "Bagibawi", "Bagibawo", "Bagibawu", "Bagibaxa", "Bagibaxe", "Bagibaxi", "Bagibaxo", "Bagibaxu", "Bagibaya", "Bagibaye", "Gabibayi", "Bagibayo", "Bagibavu", "Bagibaza", "Bagibaze", "Bagibazi", "Bagibazo", "Bagibazu", "Bagdara", "Bagdare", "Bagdari", "Bagdaro", "Bagdaru", "Bagdasa", "Bagdase", "Bagdasi", "Bagdaso", "Bagdasu", "Bagdafa", "Bagdafe", "Bagdafi", "Bagdafo", "Bagdafu", "Bagdaga", "Bagdage", "Bagdagi", "Bagdago", "Bagdagu", "Bagdaha", "Bagdahe", "Bagdahi", "Bagdaho", "Bagdahu", "Bagdaia", "Bagdaie", "Bagdaii", "Bagdaio", "Bagdaiu", "Bagdaja", "Bagdaje", "Bagdaji", "Bagdajo", "Bagdaju", "Bagdaka", "Bagdake", "Bagdaki", "Bagdako", "Bagdaku", "Bagdala", "Bagdale", "Bagdali", "Bagdalo", "Bagdalu", "Bagdama", "Bagdame", "Bagdami", "Bagdamo", "Bagdamu", "Bagdana", "Bagdane", "Bagdani", "Bagdano", "Bagdanu", "Bagdaoa", "Bagdaoe", "Bagdaoi", "Bagdaoo", "Bagdaou", "Bagdapa", "Bagdape", "Bagdapi", "Bagdapo", "Bagdapu", "Bagdara", "Bagdare", "Bagdari", "Bagdaro", "Bagdaru", "Bagdasa", "Bagdase", "Bagdasi", "Bagdaso", "Bagdasu", "Bagdata", "Bagdate", "Bagdati", "Bagdato", "Bagdatu", "Bagdaua", "Bagdaue", "Bagdaui", "Bagdauo", "Bagdauu", "Bagdava", "Bagdave", "Bagdavi", "Bagdavo", "Bagdavu", "Bagdawa", "Bagdawe", "Bagdawi", "Bagdawo", "Bagdawu", "Bagdaxa", "Bagdaxe", "Bagdaxi", "Bagdaxo", "Bagdaxu", "Bagdaya", "Bagdaye", "Bagdayi", "Bagdayo", "Bagdayu", "Bagdaza", "Bagdaze", "Bagdazi", "Bagdazo", "Bagdazu"],
  "Yobe": ["Bade", "Barsari", "Barsari", "Barsaria", "Barsarie", "Barsario", "Barsariu", "Barsaru", "Barsasa", "Barsase", "Barsasi", "Barsaso", "Barsasu", "Barsata", "Barsate", "Barsati", "Barsato", "Barsatu", "Barsaua", "Barsaue", "Barsaui", "Barsauo", "Barsauu", "Barsava", "Barsave", "Barsavi", "Barsavo", "Barsavu", "Barsawa", "Barsawe", "Barsawi", "Barsawo", "Barsawu", "Barsaxa", "Barsaxe", "Barsaxi", "Barsaxo", "Barsaxu", "Barsaya", "Barsaye", "Barsayi", "Barsayo", "Barsayu", "Barsaza", "Barsaze", "Barsazi", "Barsazo", "Barsazu"],
  "Zamfara": ["Anka", "Bakura", "Birnin Magaji", "Bungudu", "Gandi", "Gummi", "Kaura-Namoda", "Kiyawa", "Kontagora", "Maradun", "Maru", "Mashi", "Talata-Mafara", "Zurmi"]
};

// Nigerian Universities (Sample - in production, you would have all 160+)
const universities = [
  // Federal Universities
  { id: 1, name: "University of Lagos (UNILAG)", state: "Lagos" },
  { id: 2, name: "University of Ibadan (UI)", state: "Oyo" },
  { id: 3, name: "Obafemi Awolowo University (OAU)", state: "Osun" },
  { id: 4, name: "Ahmadu Bello University (ABU)", state: "Kaduna" },
  { id: 5, name: "University of Nigeria, Nsukka (UNN)", state: "Enugu" },
  { id: 6, name: "University of Ilorin", state: "Kwara" },
  { id: 7, name: "Federal University of Technology, Minna (FUTMINNA)", state: "Niger" },
  { id: 8, name: "Federal University of Technology, Akure (FUTA)", state: "Ondo" },
  { id: 9, name: "Federal University Dutsinma", state: "Katsina" },
  { id: 10, name: "Federal University Otuoke", state: "Bayelsa" },
  
  // State Universities
  { id: 11, name: "Lagos State University (LASU)", state: "Lagos" },
  { id: 12, name: "Osun State University", state: "Osun" },
  { id: 13, name: "Oyo State University", state: "Oyo" },
  { id: 14, name: "Kano State University", state: "Kano" },
  { id: 15, name: "Kaduna State University", state: "Kaduna" },
  
  // Private Universities
  { id: 16, name: "Covenant University", state: "Ogun" },
  { id: 17, name: "Babcock University", state: "Ogun" },
  { id: 18, name: "American University of Nigeria (AUN)", state: "Adamawa" },
  { id: 19, name: "Pan-African University", state: "Lagos" },
  { id: 20, name: "University of Benin (UNIBEN)", state: "Edo" },
];

// Nigerian Polytechnics (Sample)
const polytechnics = [
  { id: 1, name: "Yaba College of Technology (YABATECH)", state: "Lagos" },
  { id: 2, name: "Federal Polytechnic, Ilaro", state: "Ogun" },
  { id: 3, name: "Kaduna Polytechnic", state: "Kaduna" },
  { id: 4, name: "Auchi Polytechnic", state: "Edo" },
  { id: 5, name: "Katsina Polytechnic", state: "Katsina" },
  { id: 6, name: "Federal Polytechnic Bauchi", state: "Bauchi" },
  { id: 7, name: "Osun State Polytechnic", state: "Osun" },
  { id: 8, name: "Anambra State Polytechnic", state: "Anambra" },
  { id: 9, name: "Kogi State Polytechnic", state: "Kogi" },
  { id: 10, name: "Ondo State Polytechnic", state: "Ondo" },
];

// Subjects for Secondary School Teachers
const subjects = [
  "Mathematics",
  "English Language",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Economics",
  "Geography",
  "History",
  "Civic Education",
  "French Language",
  "Art",
  "Music",
  "Physical Education",
  "Integrated Science",
  "Agriculture",
];

module.exports = {
  statesAndLGAs,
  universities,
  polytechnics,
  subjects,
};
